name: website_bengkel_robot
description: Website Bengkel Robot
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # The Font Awesome Icon pack
  font_awesome_flutter: ^8.5.0

  # A set of widgets that can be used to define a readable responsive UI for widgets.
  responsive_builder: ^0.1.4

  # Flutter plugin for launching a URL on Android and iOS. Supports web, phone, SMS, and
  # email schemes.
  url_launcher: ^5.4.1

  # Flutter widgets that make it easy to implement the BLoC design pattern. Built to be used with
  # the bloc state management package
  flutter_bloc: ^2.1.1

  # A powerful http client for Dart, which supports interceptors, FormData, Request Cancellation,
  # File Downloading, Timeout etc.
  dio: ^3.0.7

  # Flutter library to load and cache networ images. Can also be used with placeholder and
  # error widgets.
  cached_network_image: ^1.1.3

  # An abstract class that helps to implement equality without needing to explicitly
  # override == and hashCode.
  equatable: ^1.0.1

  # Flutter widget that automatically resizes text to fit perfectly withing its bounds.
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mock library for Dart inspired by Mockito.
  mockito: ^4.1.1

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.2.4

  # Tools to write binaries that run builders.
  build_runner: ^1.7.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
