version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Run unit test
          command: flutter test
