version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter

    steps:
      - checkout

      - run:
          name: Flutter Doctor
          command: flutter doctor -v

      - run:
          name: Flutter Packages Get
          command: flutter packages get

      - run:
          name: Flutter Test
          command: flutter test
